// @header
// @copyright
// @brief
// @note 
#version 450

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct LightData
{
    // parameters[]
    int type;
    vec3 position;
    vec3 ambient;
    vec3 diffuse;
    vec3 specular;
};

layout(binding = 2) buffer GPULight
{
    LightData light[];
} lights;

vec3 computeDirctionalLight(LightData light, vec3 normal, vec3 viewDir);
vec3 computePointLight(LightData light, vec3 normal, vec3 viewDir);
vec3 computeSpotLight(LightData light, vec3 normal, vec3 viewDir);

void main()
{
    vec3 viewDir = normalize(viewPos - FragPos);
    uint index = gl_GlobalInvocationID.x;
    LightData light = lights.light[index];
    vec3 result;
    if (light.type == 0)
    {
        result += computeDirctionalLight(light, normal, viewDir);
    }
    else if (light.type == 1)
    {
        result += computePointLight();
    }
    else if (light.type == 2)
    {
        result += computeSpotLight();
    }
    else
    {
        result += computeDirctionalLight();
    }


}

vec3 computeDirctionalLight(LightData light, vec3 normal, vec3 viewDir)
{
    vec3 lightDir = normalize(-light.direction);
    float diff = max(dot(normal, lightDir), 0.0);
    vec3 reflectDir = reflect(-lightDir, normal);
    float spec = pow(max(dot(viewDir, reflectDir), 0.0), material.shininess);
    vec3 ambient = light.ambient * vec3(texture(material.diffuse, TexCoords));
    vec3 diffuse = light.diffuse * diff * vec3(texture(material.diffuse, TexCoords));
    vec3 specular = light.specular * spec * vec3(texture(material.specular, TexCoords));
    return (ambient + diffuse + specular);
}

vec3 computePointLight(LightData light, vec3 normal, vec3 viewDir)
{}

vec3 computeSpotLight(LightData light, vec3 normal, vec3 viewDir)
{}
