java_binary(
    name = "TestJ1",
    srcs = glob(["src/main/java/com/example/*.java"]),
    main_class = "com.example.TestJ1",
)


# In the same BUILD file

#java_toolchain(
#    name = "java25_toolchain",
#    runtime = ":jdk25",
#    # Other necessary attributes like source/target compatibility can be set here
#    source_version = "25",
#    target_version = "25",
#    visibility = ["//visibility:public"],
#)